version: 2
updates:
  - package-ecosystem: "go" # See documentation for possible values
    directory: "/cli" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "pnpm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "rust" # See documentation for possible values
    directory: "/shim" # Location of package manifests
    schedule:
      interval: "weekly"
